### ISSUE TITLE
v2.0.0 causing issue with pure prompt

### ISSUE THREAD

**Issue by number5** [getantibody/antibody#135]
My zsh/antibody setup now have random error like
`prompt_pure_setup:11: async: function definition file not found`

My guess is sometime `pure` load before the required library `zsh-async`, is there anyway to specify dependency?

Here is what my `.zshrc` looks like
```sh
source <(/usr/local/bin/antibody init)

PURE_PROMPT_SYMBOL=λ
PURE_GIT_PULL=0

antibody bundle <<EOF
mafredri/zsh-async
sindresorhus/pure
...
EOF
```

**Comment by caarlos0** [comment]
Hey @number5, the issue is that pure depends on zsh-async, and antibody doesn't guarantee the order.

You can solve this by doing:

```sh
antibody bundle mafredri/zsh-async
antibody bundle sindresorhus/pure
```

Or check how I do in my dotfiles, for example: https://github.com/caarlos0/dotfiles/blob/master/antibody/install.sh#L14-L16

This is highlighted in readme (the lack of order guarantees), but I'll improve it some time (there is an issue for that already: #132).

Anyways, thanks for using Antibody =)

**Comment by caarlos0** [comment]
(you can still comment here if you need more help)

**Comment by number5** [comment]
@caarlos0 thanks, solved by just moving the `zsh-async` out of the heredoc.

BTW, thanks for creating and maintaining `antibody`,  lightweight and get the jobs done, really enjoy using it.
