### ISSUE TITLE
Tilde and environment variables in plugin file

### ISSUE THREAD

**Issue by frankruegamer** [getantibody/antibody#252]
Antibody does not perform shell expansion, therefore executing
`antibody bundle '~/.zsh_plugins/git'`tries to lookup a repository on Github
`antibody: git clone failed for https://github.com/~/.zsh_plugins/git`

That means you will have to specify the absolute path of your local plugin folder in your plugin.txt file if you're using static loading.

It would be nice if `antibody bundle` would support environment variables or at least the tilde character.

**Comment by byteborg** [comment]
Your shell should expand the tilde. Depending on your shell, this will probably be the case (bash,...), if you use double-quotes. Single quotes inhibit the shell's variable expansion.

Does
`antibody bundle "~/.zsh_plugins/git"`
work?

**Comment by caarlos0** [comment]
the problem is the quotes around the parameter. `~` will not expand between quotes.

you can confirm that:

```sh
echo ~
echo '~'
echo "~"
```

**Comment by coldis** [comment]
I think the problem is that the suggested usage of `antibody bundle < ~/.zsh_plugins.txt` doesn't expand the ~ in any of lines in the txt file.

I get around this by using `sed` to expand the location of my local plugins.

`cat $DOTFILES_REPO/zsh/.zsh_plugins.txt | sed 's@%LOCAL%@'"$DOTFILES_REPO"'@' | antibody bundle`
