### ISSUE TITLE
Archive the repo?

### ISSUE THREAD

**Issue by marlonrichert** [getantibody/antibody#384]
Since you are deprecating Antibody, should you perhaps also archive the repo? That seems to be what other projects on GitHub have done when they closed down.

**Comment by caarlos0** [comment]
yeah, will do after a couple of weeks...

**Comment by podfinkx** [comment]
Hi, I really appreciate your work with antibody and is sad that is being deprecated. I don't think there is a better 
plugin-manager/plugin-loader for zsh and I confirm it trying some other alternatives. With antibody I was able to get a shell in less than a second maybe 1 second sometimes when my IO was going crazy because other task I was doing in the background. I tried with zplug and I have to wait 2.93 seconds to actually get a shell... regardless I thank you so much :pray: it was good while it lasted. 

PD: being able to define my plugins on a plain text file and source it trough antibody itself is a blast, I don't yet find other plugin-manager that does that.

**Comment by marlonrichert** [comment]
@podfinkx [Znap](https://github.com/marlonrichert/zsh-snap) can reduce your shell's startup time to ~40ms with but a single command (`znap prompt`). Just saying… 😉

**Comment by caarlos0** [comment]
you should probably use static loading with zplug, which should make it fast @podfinkx too :)

**Comment by seagle0128** [comment]
SAD! But could you please let me know which plugin manager you recommend? Thanks!

**Comment by marlonrichert** [comment]
@seagle0128 If you want something simple & light-weight, yet fast, I would recommend [Znap](https://github.com/marlonrichert/zsh-snap). 🙂

**Comment by seagle0128** [comment]
> @seagle0128 If you want something simple & light-weight, yet fast, I would recommend [Znap](https://github.com/marlonrichert/zsh-snap). 🙂

Thanks! Will try it.

**Comment by ashleyconnor** [comment]
@caarlos0 thank you for your work on this project. I've been using it for the last two years and it's been great.

I'll check out https://github.com/zplug/zplug

**Comment by marlonrichert** [comment]
@ashleyconnor Zplug’s development [has pretty much died off](https://github.com/zplug/zplug/graphs/code-frequency), leaving it with over 100 open issues and 25+ unresolved PRs. I would recommend trying [Znap](https://github.com/marlonrichert/zsh-snap) instead.

**Comment by seagle0128** [comment]
How about [zinit](https://github.com/zdharma/zinit)?

https://github.com/zdharma/zinit

**Comment by marlonrichert** [comment]
@seagle0128 Zinit is the reason I wrote Znap. Zinit does so much extra behind the scenes that it can unintentionally change the behavior of your plugins. Plus, while it is very powerful and can be very fast, it takes quite a bit of effort to make it do what you want. Put that all together and I just got fed up with it. I decided to write something way simpler that's equally fast, but has none of the extra baggage. The result is [Znap](https://github.com/marlonrichert/zsh-snap). Try it! 🙂

**Comment by rossmacarthur** [comment]
One of the best ways to make your shell load faster is to defer loading of plugins that are not critical. I can recommend [romkatv/zsh-defer](https://github.com/romkatv/zsh-defer) for this, it is plugin manager agnostic and works very well. I have used it quite successfully in conjunction with my plugin manager [sheldon](https://github.com/rossmacarthur/sheldon).

**Comment by marlonrichert** [comment]
@rossmacarthur I respectfully disagree. 🙂 If you use `zsh-defer` (or `zinit`’s “turbo mode”), you have to apply this separately for every plugin you want to load asynchronously. Not only that, you might have to add additional workarounds to make sure everything still gets executed in the right order.

Instead, you can just use `znap prompt <prompt theme>` near the top of your `.zshrc` file and Boom: You’re at the prompt in ~40ms, while the rest of your `.zshrc` continues to be executed as normal.

**Comment by caarlos0** [comment]
It seems there isn't a clear replacement for antibody yet... is this assessment correct?

If so, I can instead put it in maintenance mode (no new features, only bug fixes) for some time.

Or, if someone wants to pick it up... let me know :) 

WDYT?

**Comment by dberlin** [comment]
I think that is probably the right move (and thank you!).  I don't think you need new features (it works great).

**Comment by borekb** [comment]
@caarlos0 Oh, didn't know this is happening, I loved using Antibody! Thanks for all the time you've put into this. 🙏

For others reading this, I just spent some time migrating to Znap by @marlonrichert and I'm happy to report that it went well – most of the work was replacing `antibody bundle` with `znap source`, it clones Git repos behind the scenes (at no point I had to run `znap ...` commands in the terminal manually).

I'm especially happy about the trick with an async prompt, it's nice to see it immediately (I think nvs was partly to blame for slow startup previously, and it was also one of the exceptions where I actually had to do some changes to my `.zshrc` due to how Znap works, see https://github.com/jasongin/nvs/issues/195).
